FROM registry.opensuse.org/opensuse/tumbleweed:latest
RUN ["/usr/bin/zypper", "dup", "-y"]
RUN ["/usr/bin/zypper", "in", "-y", "firefox", "shadow", "libcanberra-gtk3-module"]
RUN ["/usr/bin/zypper", "in", "-y", "-t", "pattern", "fonts"]
RUN ["/usr/sbin/useradd", "-l", "-m", "steph"]
COPY ["./machine-id", "/etc/machine-id"]
ENTRYPOINT ["/usr/bin/firefox"]
