FROM registry.opensuse.org/opensuse/tumbleweed:latest
RUN ["/usr/bin/zypper", "in", "-y", "firefox", "shadow", "libcanberra-gtk3-module"]
RUN ["/usr/sbin/useradd", "-l", "-m", "steph"]
COPY ["./machine-id", "/etc/machine-id"]
#CMD 
ENTRYPOINT ["/usr/bin/bash"]
